# Generated by Django 4.1.5 on 2023-03-14 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert')], max_length=9)),
                ('allergy_type', models.CharField(blank=True, choices=[('FISH', 'Fish'), ('MEAT', 'Meat'), ('GRAIN', 'Grain'), ('HONEY', 'Honey'), ('NUTS', 'Nuts'), ('LACTOSE', 'Lactose')], max_length=9)),
                ('menu_type', models.CharField(choices=[('CLASSIC', 'Classic'), ('LOW CARB', 'Low Carb'), ('VEGETERIAN', 'Vegeterian'), ('KETO', 'Keto')], max_length=10)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
