# Generated by Django 4.1.5 on 2023-03-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_by',
            new_name='user',
        ),
    ]
