# Generated by Django 4.1.5 on 2023-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ingredient_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
