# Generated by Django 4.1.5 on 2023-03-16 16:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ingredient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergy_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('FISH', 'Fish'), ('MEAT', 'Meat'), ('GRAIN', 'Grain'), ('HONEY', 'Honey'), ('NUTS', 'Nuts'), ('LACTOSE', 'Lactose')], max_length=12),
        ),
    ]
