# Generated by Django 4.1.5 on 2023-03-16 16:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_recipe_allergy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergy_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('FISH', 'Fish'), ('MEAT', 'Meat'), ('GRAIN', 'Grain'), ('HONEY', 'Honey'), ('NUTS', 'Nuts'), ('LACTOSE', 'Lactose')], max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
