# Generated by Django 4.1.5 on 2023-03-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_ingredient_user_remove_ingredient_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
